# Generated by Django 4.0.6 on 2022-08-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_customuser_alter_picture_user_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.EmailField(max_length=254, unique=True, verbose_name='password'),
        ),
    ]
