# Generated by Django 4.0.6 on 2022-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20, verbose_name='password'),
        ),
    ]
