# Generated by Django 4.0.6 on 2022-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.CharField(default='', max_length=240),
        ),
    ]
