# Generated by Django 4.0.6 on 2022-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=220, verbose_name='password'),
        ),
    ]
