# Generated by Django 4.0.6 on 2022-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='default.png', upload_to='./product_pics'),
        ),
    ]
