# Generated by Django 4.0.6 on 2022-08-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.CharField(default='default.png', max_length=300),
        ),
    ]
