# Generated by Django 4.0.6 on 2022-08-14 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='artist_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
