# Generated by Django 4.0.6 on 2022-08-14 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_alter_picture_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='artist_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), default=list, size=None),
        ),
    ]
