# Generated by Django 4.0.6 on 2022-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_alter_picture_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
