# Generated by Django 4.0.6 on 2022-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_picture_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='becca', max_length=20, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='test', max_length=30, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
