# Generated by Django 4.0.6 on 2022-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='becca32', max_length=30, verbose_name='username'),
            preserve_default=False,
        ),
    ]
