# Generated by Django 4.0.6 on 2022-08-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='match',
            field=models.IntegerField(default=0),
        ),
    ]
