# Generated by Django 4.0.6 on 2022-08-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_picture_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.CharField(default='', max_length=40)),
                ('artist', models.CharField(default='', max_length=40)),
                ('picture_pk', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='art.picture')),
            ],
        ),
    ]
