# Generated by Django 4.1.3 on 2023-02-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
